### ISSUE TITLE
Localization not working?

### ISSUE THREAD

**Issue by tgstyle** [Azanor/Baubles#181] opened 2016-12-15 01:42 UTC
Not a big issue as it is just your sample anyway. However, in 1.10.2 - 1.3.8, looks like the ring is not rendering.

**Comment by tgstyle** [comment] 2017-02-22 20:05
It appears to be localization? None of the names in the mod are working, the ring is missing the texture. 1.3.9 still has the issue. This is at least true for en_US

**Comment by SnowShock35** [comment] 2017-05-04 16:05
It seems that 1.3.10 attempted to fix this issue and did not either 😕

**Comment by oitsjustjose** [comment] 2017-05-09 00:31
So oddly enough, this problem was _fixed_ for me when I first installed this update, but I just noticed today that it had broken itself again.. not sure what's up, I've restarted my client a few times and the mod version and install locations haven't been changed, so I'm super confused...

Unless one of the mods using Baubles is packaging Baubles with it..?

**Comment by Azanor** [comment] 2017-05-09 10:19
I'm trying to figure out why this is happening. Baubles on its own seems to work fine, but the moment other mods get thrown into the mix the localization bugs out. Very strange - it is not like I am doing anything unusual with it or even touched that code.

**Comment by oitsjustjose** [comment] 2017-05-09 14:29
I've spent about 2 hours in the dev environment for Baubles and I can't figure it out. What I did, however, manage to do is fix it in a not-so-pretty way. 

I wouldn't be surprised if this bug was caused by I18n, but I'm not certain; that being said, it _is_ deprecated so maybe this is the reason why? I honestly can't tell, you're using localizations exactly the same way as I do, and the encoding type of your .lang files is perfectly fine. Running `I18n.canTranslate()` returns `false` every time in Baubles, so I'm truly confused, but [I use it in my mod and it works just fine](https://github.com/oitsjustjose/Pulver/blob/master/src/main/java/com/oitsjustjose/pulver/items/ItemDust.java#L55-L61). 

That being said, this is what I've put together, and it seems to work:
`	@SideOnly(Side.CLIENT)
	public static String getTranslation(String toTranslate)
	{
		InputStream in = Baubles.class.getResourceAsStream("/assets/baubles/lang/" + Minecraft.getMinecraft().gameSettings.language + ".lang");
		try
		{
			for (String s : IOUtils.readLines(in))
				if (s.contains(toTranslate))
					return s.replace(toTranslate + "=", "");
		}
		catch (IOException e)
		{
		}
		return toTranslate;
	}`


That being said,

1: I know this isn't formatted how you like, and

2: You've gotta be pretty careful with implementing this since it uses client-side only methods. I can't imagine it being a huge deal, but just always gotta be cautious. But you're a fantastic modder, so you shouldn't have a problem with this. 

**Side note: ring texture is broken because Ring.json needs to be lowercased to ring.json**

**Comment by Xalcon** [comment] 2017-05-12 21:10
just a fyi, i made a pull request to fix the issues for 1.11.2.

**Comment by Azanor** [comment] 2017-05-25 06:51
Doh, yeah - the localization files needs to be all lowercase as well. I forgot about that. Thanks for the fix.

**Comment by oitsjustjose** [comment] 2017-05-25 12:15
Will this be fixed on 1.10.2? I'm not sure what the issue was there, but it still persists - not that it's a huge deal!

**Comment by Azanor** [comment] 2017-05-25 12:24
Oops, was not aware it still occurred in 1.10 as well. Should be a similar fix.

**Closed** 2017-05-25 12:40 UTC
Labels: bug

**Comment by oitsjustjose** [comment] 2017-05-25 12:49
Hate to be the bearer of bad news, but still no cigar:


![2017-05-25_08 47 47](https://cloud.githubusercontent.com/assets/3887324/26450762/fa3d410e-4126-11e7-8855-1715f238782a.png)



![2017-05-25_08 47 57](https://cloud.githubusercontent.com/assets/3887324/26450765/fda6e980-4126-11e7-8aed-9da467330f7d.png)


This is on 1.3.1.1 - I have no idea what it could be aside from what I could distinguish a few weeks ago.

**Comment by SnowShock35** [comment] 2017-05-25 15:33
1.10.2 - Still Broken
1.11.2 - Perfectly fine all working.

**Comment by Xalcon** [comment] 2017-05-25 17:26
I guess there was an misunderstanding with my pull-request. Minecraft 1.10.2 still uses the Resourcepack Format v2, which **requires** lang files to be in the format `ab_CD`. Only v3 (1.11+) wants them to be all lowercase.

I've just tested this in my development environment. If the lang files have said format, the localisation works fine.

**Comment by SnowShock35** [comment] 2017-05-25 19:59
@Xalcon Oh yeah 😛 so just need to recapitalise the lang files and change pack.mcmeta version to 2

**Comment by tofof** [comment] 2017-05-28 02:16
@Azanor ping
Confirmed, 1.10.2 needs capitalized format (and should probably be v2).
