### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Simuciokas** [Azanor/Baubles#92] opened 2015-02-11 17:41 UTC
Log: http://pastebin.com/f1NKUA3d

**Comment by Azanor** [comment] 2015-02-12 06:45
Hmmm, I'll take a look

**Comment by gigabit101** [comment] 2015-02-12 11:35
@Azanor it seems to be a change in the new versions of forge

**Comment by Jamerboy** [comment] 2015-02-14 10:21
Nope, it's actually caused by registering the renders serverside

**Comment by JonnyBrando** [comment] 2015-02-25 15:46
Jamerboy, when I grab your source and compile it, the server-side works but the client-side crashes with CodeChickenCore and NotEnoughItems.

http://pastebin.com/qUc1Hb65

**Comment by Azanor** [comment] 2015-03-02 08:15
This has been fixed in the 1.1.1.0 version of baubles. That would teach me to not blindy accept commits and only test them in a single player game  :p

**Closed by Azanor** 2015-03-02 08:15 UTC
